apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # The argo CD project this application belongs to
  project: default

  source:
    repoURL: https://github.com/Roboshop-2/argocd-v1.git
    targetRevision: main
    path: applications/cluster/rbac

  # Destination configuration pointing to the target cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true       # Automatically deletes resources no longer in Git
      selfHeal: true  